/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.guicoursework;

import java.awt.Label;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author supun
 */
public class OrderStatus extends javax.swing.JFrame {

    /**
     * Creates new form OrderStatus
     */
    public OrderStatus() {
        initComponents();
        orderid.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        orderid = new javax.swing.JTextField();
        size = new javax.swing.JLabel();
        qty = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnstatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stattus Form");
        setPreferredSize(new java.awt.Dimension(550, 450));

        Cid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Enter Order Id : ");

        amount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        orderid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        orderid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderidActionPerformed(evt);
            }
        });
        orderid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                orderidKeyPressed(evt);
            }
        });

        size.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        qty.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnBack1.setBackground(new java.awt.Color(255, 102, 102));
        btnBack1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Customer ID    :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Size                    :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Amount            :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Status               :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("QTY                  :");

        status.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnSearch.setBackground(new java.awt.Color(0, 153, 102));
        btnSearch.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        btnSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSearchKeyPressed(evt);
            }
        });

        btnstatus.setBackground(new java.awt.Color(51, 153, 255));
        btnstatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnstatus.setForeground(new java.awt.Color(255, 255, 255));
        btnstatus.setText("Change Status");
        btnstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstatusActionPerformed(evt);
            }
        });
        btnstatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnstatusKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(size, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(orderid, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Cid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnstatus)
                .addGap(38, 38, 38))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, jLabel6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Cid, amount, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, qty, size, status});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        ArrayList<Orders> list = Home.orderList;
        String orderId = orderid.getText();

        int x = 0;
        boolean found = false;
        for (Orders id : list) {
            if (id.getIdNumber().equals(orderId)) {
                for (int i = 0; i < list.size(); i++) {
                    Orders tempray = list.get(i);
                    if (id.getIdNumber().equals(tempray.getIdNumber())) {
                        x = i;
                    }
                }
                found = true;
                break;
            }
        }
        if (found) {
            Orders tempary = list.get(x);
            Cid.setText(tempary.getPhoneNumber());
            size.setText(tempary.getSize());
            qty.setText(Integer.toString(tempary.getQty()));
            amount.setText(Double.toString(tempary.getAmount()));
            status.setText(tempary.getStatus());
            btnstatus.requestFocus();
        }
        if (!found) {
            int ok = JOptionPane.showConfirmDialog(this, "Invalid ID..", "Error", JOptionPane.OK_OPTION);
            if (ok == JOptionPane.OK_OPTION) {
                Cid.setText("");
                size.setText("");
                qty.setText("");
                amount.setText("");
                status.setText("");
                orderid.requestFocus();

            } else {
                dispose();
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstatusActionPerformed
        ArrayList<Orders> list = Home.orderList;
        String orderId = orderid.getText();
        Orders od = new Orders(orderId);
        int x = list.indexOf(od);
        Orders tempary = list.get(x);
        String statusName[] = {"Delivaring", "Delivered"};
        String statusName2[] = {"Delivered"};
        if (tempary.getStatus().equals("Processing")) {
            int st = JOptionPane.showOptionDialog(null, "Please select the status", "Status", 0, JOptionPane.QUESTION_MESSAGE, null, statusName, statusName[0]);
            if (st == 0) {
                tempary.setStatus("Delivering");
                int ok = JOptionPane.showConfirmDialog(this, "Status Updated..Do you want to change anther status ?", "Success", JOptionPane.YES_OPTION);
                if (ok == 0) {

                    orderid.setText("");
                    Cid.setText("");
                    size.setText("");
                    qty.setText("");
                    amount.setText("");
                    status.setText("");
                    orderid.requestFocus();
                } else {
                    dispose();
                }

            } else if (st == 1) {
                tempary.setStatus("Delivered");
                int ok = JOptionPane.showConfirmDialog(this, "Status Updated..Do you want to change anther status ?", "Success", JOptionPane.YES_OPTION);
                if (ok == 0) {
                    orderid.setText("");
                    Cid.setText("");
                    size.setText("");
                    qty.setText("");
                    amount.setText("");
                    status.setText("");
                    orderid.requestFocus();
                } else {
                    dispose();
                }

            } else {

            }
        } else if (tempary.getStatus().equals("Delivering")) {
            int st = JOptionPane.showOptionDialog(this, "Please select the status", "Status", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE, null, statusName2, statusName2[0]);
            if (st == 0) {
                tempary.setStatus("Delivered");
                int ok = JOptionPane.showConfirmDialog(this, "Status Updated..Do you want to change anther status ?", "Success", JOptionPane.YES_OPTION);
                if (ok == 0) {
                    orderid.setText("");
                    Cid.setText("");
                    size.setText("");
                    qty.setText("");
                    amount.setText("");
                    status.setText("");
                    orderid.requestFocus();
                } else {
                    dispose();
                }
            }

        } else {
            int st = JOptionPane.showConfirmDialog(this, "Can't change this order status , Order already delivered..!", "Warning", JOptionPane.WARNING_MESSAGE);
            if (st == 0) {
                tempary.setStatus("Delivered");
                int ok = JOptionPane.showConfirmDialog(this, "Do you want to change anther status ?", "Success", JOptionPane.YES_OPTION);
                if (ok == 0) {
                    Cid.setText("");
                    orderid.setText("");
                    size.setText("");
                    qty.setText("");
                    amount.setText("");
                    status.setText("");
                    orderid.requestFocus();
                } else {
                    dispose();
                }

            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnstatusActionPerformed
    private void btnstatusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnstatusKeyPressed
//        Orders tempary = new Orders(orderid.getText());
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
        ArrayList<Orders> list = Home.orderList;
        String orderId = orderid.getText();
        Orders od = new Orders(orderId);
        int x = list.indexOf(od);
        Orders tempary = list.get(x);
        String statusName[] = {"Delivaring", "Delivered"};
        String statusName2[] = {"Delivered"};
        if (tempary.getStatus().equals("Processing")) {
            int st = JOptionPane.showOptionDialog(this, "Please select the status", "Status", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, statusName, statusName[0]);
//            System.out.println(st);
            if (st == 0) {
                tempary.setStatus("Delivering");
                int ok = JOptionPane.showConfirmDialog(this, "Status Updated..Do you want to change anther status ?", "Success", JOptionPane.YES_OPTION);
                if (ok == 0) {

                    orderid.setText("");
                    Cid.setText("");
                    size.setText("");
                    qty.setText("");
                    amount.setText("");
                    status.setText("");
                    orderid.requestFocus();
                } else {
                    dispose();
                }

            } else if (st == 1) {
                tempary.setStatus("Delivered");
                int ok = JOptionPane.showConfirmDialog(this, "Status Updated..Do you want to change anther status ?", "Success", JOptionPane.YES_OPTION);
                System.out.println(ok);
                if (ok == 0) {
                    orderid.setText("");
                    Cid.setText("");
                    size.setText("");
                    qty.setText("");
                    amount.setText("");
                    status.setText("");
                    orderid.requestFocus();
                } else {
                    dispose();
                }

            } else {

            }
        } else if (tempary.getStatus().equals("Delivering")) {
            int st = JOptionPane.showOptionDialog(this, "Please select the status", "Status", 0, JOptionPane.QUESTION_MESSAGE, null, statusName2, statusName2[0]);
            if (st == 0) {
                tempary.setStatus("Delivered");
                int ok = JOptionPane.showConfirmDialog(this, "Status Updated..Do you want to change anther status ?", "Success", JOptionPane.YES_OPTION);
                if (ok == 0) {
                    orderid.setText("");
                    Cid.setText("");
                    size.setText("");
                    qty.setText("");
                    amount.setText("");
                    status.setText("");
                    orderid.requestFocus();
                } else {
                    dispose();
                }
            }

        } else {
            int st = JOptionPane.showConfirmDialog(this, "Can't change this order status , Order already delivered..!", "Warning", JOptionPane.WARNING_MESSAGE);
            if (st == 0) {
                tempary.setStatus("Delivered");
                int ok = JOptionPane.showConfirmDialog(this, "Do you want to change anther status ?", "Success", JOptionPane.YES_OPTION);
                if (ok == 0) {
                    Cid.setText("");
                    orderid.setText("");
                    size.setText("");
                    qty.setText("");
                    amount.setText("");
                    status.setText("");
                    orderid.requestFocus();
                } else {
                    dispose();
                }

            }

        }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnstatusKeyPressed

    private void orderidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_orderidKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
            btnSearchActionPerformed(null);
        }
    }//GEN-LAST:event_orderidKeyPressed

    private void btnSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
//            ArrayList<Orders> list = Home.orderList;
//            String orderId = orderid.getText();
//
//            int x = 0;
//            boolean found = false;
//            for (Orders id : list) {
//                if (id.getIdNumber().equals(orderId)) {
//                    for (int i = 0; i < list.size(); i++) {
//                        Orders tempray = list.get(i);
//                        if (id.getIdNumber().equals(tempray.getIdNumber() )) {
//                            x = i;
//                        }
//                    }
//                    found = true;
//                    break;
//                }
//            }
//            if (found) {
//                Orders tempary = list.get(x);
//                Cid.setText(tempary.getPhoneNumber());
//                size.setText(tempary.getSize());
//                qty.setText(Integer.toString(tempary.getQty()));
//                amount.setText(Double.toString(tempary.getAmount()));
//                status.setText(tempary.getStatus());
//                btnstatus.requestFocus();
//            }
//            if (!found) {
//                int ok = JOptionPane.showConfirmDialog(this, "Invalid ID..", "Error", JOptionPane.OK_OPTION);
//                if (ok == JOptionPane.OK_OPTION) {
//                    dispose();
//                    new OrderStatus().setVisible(true);
//                } else {
//                    dispose();
//                }
//            }
            btnSearchActionPerformed(null);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchKeyPressed

    private void orderidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderidActionPerformed
//            btnSearchActionPerformed(null);

    }//GEN-LAST:event_orderidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderStatus.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderStatus.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderStatus.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderStatus.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cid;
    private javax.swing.JLabel amount;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField orderid;
    private javax.swing.JLabel qty;
    private javax.swing.JLabel size;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
